import type { Metadata } from "next";
import { Geist, Geist_Mono, Pacifico } from "next/font/google";
import "./globals.css";
import Script from 'next/script';

const pacifico = Pacifico({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-pacifico',
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Readdy Site",
  description: "Generated by Readdy",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${pacifico.variable} antialiased`}
      >
        {children}
        <Script 
          src="https://readdy.ai/api/public/assistant/widget?projectId=0361743c-d6ab-494c-8439-5a780936c064"
          strategy="afterInteractive"
          mode="hybrid"
          voice-show-transcript="true"
          theme="light"
          size="compact"
          accent-color="#16a34a"
          button-base-color="#15803d"
          button-accent-color="#ffffff"
        />
      </body>
    </html>
  );
}
